name: Publish Artifacts
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Publish artifacts to JFrog
        uses: jfrog/setup-jfrog-cli@v1
        with:
        server-id: jfrog
        server-url: ${{ secrets.JFROG_URL }}
        user: ${{ secrets.JFROG_USER }}
        password: ${{ secrets.JFROG_PASSWORD }}
      run: |
        jfrog rt upload target/*.jar my-local-repo/ --flat=true
      

 
